### ISSUE TITLE
Clarification on GPT-4 Versions for Evaluation

### ISSUE THREAD

**Issue by X1AOX1A** [ConiferLM/Conifer#7]
Hello Conifer Authors,

Could you please clarify the specific versions of GPT-4 used during the evaluation process? Specifically, I’m looking for the exact versions used in:

- FollowBench (e.g., gpt-4-xxxx)
- AlpacaEval2 (e.g., gpt4_turbo-xxxx for the baseline, and a confirmation that the annotator is set to `weighted_alpaca_eval_gpt4_turbo`)
- InfoBench (e.g., gpt-4-0314)
- MT-bench (e.g. gpt-4-xxxx)

For reference, here is the official list of GPT-4 version names provided by OpenAI: [GPT-4 Model Documentation](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4).

Thank you for your help!

**Comment by moyu-hrsun** [comment]
Hi, I apologize that I’m unable to confirm the exact versions we used during evaluation, as we can only make an approximate guess. 
For evaluations on **FollowBench** and **InfoBench**, we used `gpt-4-turbo`, which likely point to `gpt-4-1106-preview` at the time of our experiments. For **MT-Bench**, we used `gpt-4-0314`. For **AlpacaEval2**, we followed the official repository's scripts, where `gpt-4-turbo` likely pointed to `gpt-4-0125-preview` at the time of evaluation.. The annotator was configured as `weighted_alpaca_eval_gpt4_turbo`.

**Comment by X1AOX1A** [comment]
Thanks for your reply! Great appreciated!

**Comment by X1AOX1A** [comment]
Hi, I still have some confusion regarding the model versions used in FollowBench and InfoBench.

In the FollowBench paper, they reference using `GPT-4-Preview-1106`. However, in the code, the model is set to [gpt-4](https://github.com/YJiangcm/FollowBench/blob/5de75f22bdb697951f9833c1bdffc6984c11c231/code/llm_eval.py#L20) by default. According to [OpenAI’s documentation](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4), `gpt-4` currently points to `gpt-4-0613`, not `gpt-4-1106-preview`. Could you please confirm if the FollowBench code used for evaluation explicitly specifies `model=gpt-4-1106-preview`, or if it defaults to `model=gpt-4`, which would mean it’s actually `gpt-4-0613`?

Additionally, for InfoBench, the [instruction documentation](https://github.com/qinyiwei/InfoBench#step3-evaluation) indicates using `gpt-4-0314` (`--eval_model gpt-4-0314`). Could you confirm whether this is indeed the specific version set in the command?

Thank you for helping clarify this!

**Comment by moyu-hrsun** [comment]
Hi, sorry for the late reply. From my perspective, if we ensure that the same API version is used consistently in evaluations, it guarantees that comparisons remain fair and valid. In this case, for our evaluations, we used `gpt-4-1106-preview` to evaluate all 7B and 13B models on both FollowBench and InfoBench.

Unfortunately, we’re also not certain about the exact model versions used in the original FollowBench and InfoBench papers.

**Comment by X1AOX1A** [comment]
Got it, thanks for your detailed information.
