### ISSUE TITLE
DPO training dataset

### ISSUE THREAD

**Issue by zswuser** [ConiferLM/Conifer#8]
Hello, I would like to inquire about the scale of the UltraFeedback dataset you used during the DPO training phase. Please forgive me for not being able to find this information in the article.

**Comment by moyu-hrsun** [comment]
Hi, the dataset used for DPO training is [HuggingFaceH4/ultrafeedback_binarized](https://huggingface.co/datasets/HuggingFaceH4/ultrafeedback_binarized), which includes approximately 61.1k samples for training.

**Comment by zswuser** [comment]
Thank you for your reply!
